/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _devkp_public_h_
#define _devkp_public_h_
//---------------------------------------------------------------------------------
extern const unsigned char devkp_public[];
extern const int devkp_public_size;
//---------------------------------------------------------------------------------
#endif //_devkp_public_h_
//---------------------------------------------------------------------------------
